export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

export const FORGOT_USER_REQUEST = "FORGOT_USER_REQUEST";
export const FORGOT_USER_SUCCESS = "FORGOT_USER_SUCCESS";
export const FORGOT_USER_FAIL = "FORGOT_USER_FAIL";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_TO_CART = "REMOVE_TO_CART";

export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";

export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const MY_ORDER_REQUEST = "MY_ORDER_REQUEST";
export const MY_ORDER_SUCCESS = "MY_ORDER_SUCCESS";
export const MY_ORDER_FAIL = "MY_ORDER_FAIL";

export const ORDER_DETAIL_REQUEST = "ORDER_DETAIL_REQUEST";
export const ORDER_DETAIL_SUCCESS = "ORDER_DETAIL_SUCCESS";
export const ORDER_DETAIL_FAIL = "ORDER_DETAIL_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

//admin get products...
export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST";
export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS";
export const ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL";

//admin new product create...[NEW_REVIEW ER jaigai new product hobe..]
export const ADMIN_NEW_REVIEW_REQUEST = "ADMIN_NEW_REVIEW_REQUEST";
export const ADMIN_NEW_REVIEW_SUCCESS = "ADMIN_NEW_REVIEW_SUCCESS";
export const ADMIN_NEW_REVIEW_RESET = "ADMIN_NEW_REVIEW_RESET";
export const ADMIN_NEW_REVIEW_FAIL = "ADMIN_NEW_REVIEW_FAIL";

//admin product delete...
export const ADMIN_PRODUCT_DELETE_REQUEST = "ADMIN_PRODUCT_DELETE_REQUEST";
export const ADMIN_PRODUCT_DELETE_SUCCESS = "ADMIN_PRODUCT_DELETE_SUCCESS";
export const ADMIN_PRODUCT_DELETE_RESET = "ADMIN_PRODUCT_DELETE_RESET";
export const ADMIN_PRODUCT_DELETE_FAIL = "ADMIN_PRODUCT_DELETE_FAIL";
//admin Edit delete...
export const ADMIN_PRODUCT_EDIT_REQUEST = "ADMIN_PRODUCT_EDIT_REQUEST";
export const ADMIN_PRODUCT_EDIT_SUCCESS = "ADMIN_PRODUCT_EDIT_SUCCESS";
export const ADMIN_PRODUCT_EDIT_RESET = "ADMIN_PRODUCT_EDIT_RESET";
export const ADMIN_PRODUCT_EDIT_FAIL = "ADMIN_PRODUCT_EDIT_FAIL";
//admin get all orders ...
export const ADMIN_ALL_ORDERS_REQUEST = "ADMIN_ALL_ORDERS_REQUEST";
export const ADMIN_ALL_ORDERS_SUCCESS = "ADMIN_ALL_ORDERS_SUCCESS";
export const ADMIN_ALL_ORDERS_FAIL = "ADMIN_ALL_ORDERS_FAIL";
//admin all orders updated...
export const ADMIN_ALL_ORDERS_UPDATED_REQUEST =
  "ADMIN_ALL_ORDERS_UPDATED_REQUEST";
export const ADMIN_ALL_ORDERS_UPDATED_SUCCESS =
  "ADMIN_ALL_ORDERS_UPDATED_SUCCESS";
export const ADMIN_ALL_ORDERS_UPDATED_RESET = "ADMIN_ALL_ORDERS_UPDATED_RESET";
export const ADMIN_ALL_ORDERS_UPDATED_FAIL = "ADMIN_ALL_ORDERS_UPDATED_FAIL";
//admin all orders delete...
export const ADMIN_ALL_ORDERS_DELETED_REQUEST =
  "ADMIN_ALL_ORDERS_DELETED_REQUEST";
export const ADMIN_ALL_ORDERS_DELETED_SUCCESS =
  "ADMIN_ALL_ORDERS_DELETED_SUCCESS";
export const ADMIN_ALL_ORDERS_DELETED_RESET = "ADMIN_ALL_ORDERS_DELETED_RESET";
export const ADMIN_ALL_ORDERS_DELETED_FAIL = "ADMIN_ALL_ORDERS_DELETED_FAIL";

// admin all user request...
export const ADMIN_ALL_USER_REQUEST = "ADMIN_ALL_USER_REQUEST";
export const ADMIN_ALL_USER_SUCCESS = "ADMIN_ALL_USER_SUCCESS";
export const ADMIN_ALL_USER_FAIL = "ADMIN_ALL_USER_FAIL";

// admin all user details and user id select request...
export const ADMIN_ALL_USER_DETAILS_REQUEST = "ADMIN_ALL_USER_DETAILS_REQUEST";
export const ADMIN_ALL_USER_DETAILS_SUCCESS = "ADMIN_ALL_USER_DETAILS_SUCCESS";
export const ADMIN_ALL_USER_DETAILS_FAIL = "ADMIN_ALL_USER_DETAILS_FAIL";

//admin all user delete request...
export const ADMIN_ALL_USER_DELETE_REQUEST = "ADMIN_ALL_USER_DELETE_REQUEST";
export const ADMIN_ALL_USER_DELETE_SUCCESS = "ADMIN_ALL_USER_DELETE_SUCCESS";
export const ADMIN_ALL_USER_DELETE_FAIL = "ADMIN_ALL_USER_DELETE_FAIL";
export const ADMIN_ALL_USER_DELETE_RESET = "ADMIN_ALL_USER_DELETE_RESET";

//admin all user updated request...
export const ADMIN_ALL_USER_UPDATED_REQUEST = "ADMIN_ALL_USER_UPDATED_REQUEST";
export const ADMIN_ALL_USER_UPDATED_SUCCESS = "ADMIN_ALL_USER_UPDATED_SUCCESS";
export const ADMIN_ALL_USER_UPDATED_FAIL = "ADMIN_ALL_USER_UPDATED_FAIL";
export const ADMIN_ALL_USER_UPDATED_RESET = "ADMIN_ALL_USER_UPDATED_RESET";

// admin all user review request...
export const ADMIN_ALL_USER_REVIEW_REQUEST = "ADMIN_ALL_USER_REVIEW_REQUEST";
export const ADMIN_ALL_USER_REVIEW_SUCCESS = "ADMIN_ALL_USER_REVIEW_SUCCESS";
export const ADMIN_ALL_USER_REVIEW_FAIL = "ADMIN_ALL_USER_REVIEW_FAIL";

//admin all user deleted request...
export const ADMIN_ALL_REVIEW_DELETED_REQUEST =
  "ADMIN_ALL_REVIEW_DELETED_REQUEST";
export const ADMIN_ALL_REVIEW_DELETED_SUCCESS =
  "ADMIN_ALL_REVIEW_DELETED_SUCCESS";
export const ADMIN_ALL_REVIEW_DELETED_FAIL = "ADMIN_ALL_REVIEW_DELETED_FAIL";
export const ADMIN_ALL_REVIEW_DELETED_RESET = "ADMIN_ALL_REVIEW_DELETED_RESET";
